### PR TITLE
Coarse grained, initial sanitization

### PR DESCRIPTION
**Pull request by nazavode**
This PR introduces some basic sanitizations applied while studying the code base.

This is related to https://github.com/forthelols/4nxt/issues/85

### CODE REVIEW

**Review by alalazo — APPROVED** [review]
I had a look yesterday. LGTM.

**Comment by alalazo** [comment]
I tried to compile the code for Unix. `make` exits with non zero, but all the relevant libraries (e.g the Unix virtual driver) are there. I could start the `TestMasterSlave` application only after moving the `libcanfestival_can_virtual.so` to the place where the application expects it. It seems to run indefinitely, without exiting and with an output like:
```
...
TestSlave_post_TPDO
OnMasterMap1Update:1
1->[ 0  ]id:00 SYNC  rtr:0 len:0
TestMaster_post_sync
Master: 1 1 0 0 1 0 1 0 16 ff00ff00 abcd 2323 2322
TestMaster_post_TPDO MasterSyncCount = 1092 
TestSlave_post_sync
Slave: 1 1 0 0 1 0 1 0 16 ff00ff00 abcd 129 2326 
0->[ 1  ]id:02 PDO1tx  rtr:0 len:6 53 10 00 ff 00 ff
0->[ 1  ]id:02 PDO2tx  rtr:0 len:2 cd ab
TestSlave_post_TPDO
OnMasterMap1Update:1
1->[ 0  ]id:00 SYNC  rtr:0 len:0
TestMaster_post_sync
Master: 1 1 0 0 1 0 1 0 16 ff00ff00 abcd 2323 2322
TestMaster_post_TPDO MasterSyncCount = 1093 
TestSlave_post_sync
Slave: 1 1 0 0 1 0 1 0 16 ff00ff00 abcd 129 2327 
0->[ 1  ]id:02 PDO1tx  rtr:0 len:6 53 10 00 ff 00 ff
0->[ 1  ]id:02 PDO2tx  rtr:0 len:2 cd ab
TestSlave_post_TPDO
0->[ 1  ]id:02 EMCY  rtr:0 len:8 00 42 08 00 00 00 00 00
0->[ 1  ]id:02 EMCY  rtr:0 len:8 00 00 00 00 00 00 00 00
OnMasterMap1Update:1
Master received EMCY message. Node: 02  ErrorCode: 4200  ErrorRegister: 08
Master received EMCY message. Node: 02  ErrorCode: 0000  ErrorRegister: 00
1->[ 0  ]id:00 SYNC  rtr:0 len:0
TestMaster_post_sync
Master: 1 1 0 0 1 0 1 0 16 ff00ff00 abcd 2323 2322
TestMaster_post_TPDO MasterSyncCount = 1094 
TestSlave_post_sync

...
```

**Comment by nazavode** [comment]
@alalazo just obtained the same result on `master`, my guess is that the original build system needs to be somehow tweaked by the user before any actual use.

**Comment by alalazo** [comment]
> just obtained the same result on master, my guess is that the original build system needs to be somehow tweaked by the user before any actual use.

My impression too.

**Pull request merged**
